# Generated by Django 6.0.2 on 2026-03-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tovars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(default=300, max_length=100),
        ),
    ]
