# Generated by Django 6.0.2 on 2026-03-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tovars', '0002_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='serialnumber',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
