# Generated by Django 6.0.2 on 2026-03-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tovars', '0003_alter_product_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='игровой ноутбук.......'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(null=True, to='tovars.tag'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='ноутбук ACER', max_length=100),
        ),
        migrations.AlterField(
            model_name='reviewproduct',
            name='comment',
            field=models.TextField(default='прикольный ноутбук'),
        ),
        migrations.AlterField(
            model_name='reviewproduct',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
