# Generated by Django 6.0.2 on 2026-03-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_book', models.CharField(max_length=50, verbose_name='укажите навание книги')),
                ('description', models.TextField(verbose_name='укажите описание книги')),
                ('imagiine', models.ImageField(upload_to='book/', verbose_name='загужите обложку')),
                ('category_book', models.CharField(choices=[('фантакстика', 'фантастика'), ('хоррор', 'хоррор'), ('исторические', 'исторические')], max_length=100, verbose_name='выберите категорию')),
                ('url_audio_book', models.URLField(verbose_name='укажите ссылку на аудиокнигу')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'книги',
                'verbose_name_plural': 'книги',
            },
        ),
    ]
