# Generated by Django 6.0.2 on 2026-03-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'книгу', 'verbose_name_plural': 'книги'},
        ),
        migrations.AlterField(
            model_name='books',
            name='imagiine',
            field=models.ImageField(upload_to='books/', verbose_name='загужите обложку'),
        ),
    ]
