# Generated by Django 6.0.2 on 2026-03-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_books_options_alter_books_imagiine'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='views',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
