# Generated by Django 6.0.3 on 2026-03-05 11:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название машины')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='cars/', verbose_name='Фото')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1886), django.core.validators.MaxValueValidator(2026)])),
                ('engine_volume', models.FloatField(verbose_name='Оъем двигателя')),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('is_electric', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(default='Unknown', max_length=50)),
            ],
        ),
    ]
