# Generated by Django 6.0.3 on 2026-03-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_of_facts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
