# Generated by Django 6.0.3 on 2026-03-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('photo', models.ImageField(upload_to='drivers_photos/', verbose_name='ФОТО')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('car_choice', models.CharField(choices=[('sedan', 'Седан'), ('suv', 'Внедорожник'), ('truck', 'Грузовой')], max_length=20, verbose_name='Выбор машины')),
                ('experience', models.PositiveIntegerField(verbose_name='Водительский стаж (лет)')),
                ('has_license', models.BooleanField(default=False, verbose_name='Наличие прав (Да/Нет)')),
            ],
        ),
    ]
