# Generated by Django 6.0.3 on 2026-03-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CineBoard', '0004_alter_comment_options_remove_movie_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
