# Generated by Django 6.0.3 on 2026-03-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ITSpecialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телофона')),
                ('specialization', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('fullstack', 'Fullstack'), ('devops', 'Devops'), ('design', 'UX/UI Desing')], max_length=20, verbose_name='Специализация')),
                ('experience_years', models.PositiveIntegerField(verbose_name='Стаж работы(лет)')),
                ('github_url', models.URLField(verbose_name='Ссылка на GitHub')),
                ('portfolio_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на портфолио')),
                ('bio', models.TextField(verbose_name='О себе ')),
                ('resume', models.FileField(upload_to='resumes/', verbose_name='Файл резюме')),
                ('expected_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ожидаемая ЗП')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('is_ready_to_relocate', models.BooleanField(default=False, verbose_name='Готов к переезду')),
            ],
        ),
    ]
