# Generated by Django 6.0.2 on 2026-03-09 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_alter_books_options_alter_books_imagiine'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_order', models.CharField(default='Иван Иванов', max_length=100)),
                ('number_card', models.PositiveIntegerField()),
                ('status_order', models.CharField(choices=[('Уверен', 'Уверен'), ('Отказ', 'Отказ'), ('Подумаю', 'Подумаю')], max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('choices_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books')),
            ],
        ),
    ]
